name: CI/CD. 
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  web:
    name: web
    runs-on: ubuntu-latest
    defaults:
      run:
      # Mobile folder working directory.
        working-directory: web

    steps:
      - uses: actions/checkout@v2 

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            web:
              - 'web/**'     
              
      - name: print web
        if: steps.filter.outputs.web == 'true'
        run: echo "web"
 
  mobile:
    name: mobile
    runs-on: ubuntu-latest
    defaults:
      run:
      # Mobile folder working directory.
        working-directory: mobile

    steps:
      - uses: actions/checkout@v2 

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            mobile:
              - 'mobile/**'     
              
      - name: print mobile
        if: steps.filter.outputs.mobile == 'true'
        run: echo "Mobile"
